package com.games.bean.arithmaticker;

public class GUI {

    //REQUIRES: correct is true
    //EFFECTS: draw the correct answer onto the screen
    public void drawAnswer(){
        //TODO
    }

    //REQUIRES: incorrect is true
    //EFFECTS: draw an orange line onto the screen
    public void drawLine(){
        //TODO
    }

    //EFFECTS: draws a timer on the top left of the screen
    public void drawTimer(){
        //TODO
    }

    //REQUIRES: question has been generated by the Question class
    //EFFECTS: draws the bigNumber onto the centre of the screen with subtraction
    public void drawQuestion(){
        //TODO
    }
}